resources:
  containers:
    - container: env1604
      image: pointcloudlibrary/env:16.04

jobs:
  - job: ubuntu1604
    displayName: Ubuntu 16.04
    timeoutInMinutes: 0
    pool:
      vmImage: 'Ubuntu 16.04'
    container: env1604
    variables:
      BUILD_DIR: '$(Agent.BuildDirectory)/build'
    steps:
      - script: |
          mkdir $BUILD_DIR && cd $BUILD_DIR
          cmake $(Build.SourcesDirectory) \
            -DCMAKE_BUILD_TYPE="Release" \
            -DPCL_ONLY_CORE_POINT_TYPES=ON \
            -DPCL_WARNINGS_ARE_ERRORS=ON \
            -DBUILD_simulation=ON \
            -DBUILD_surface_on_nurbs=ON \
            -DBUILD_global_tests=ON \
            -DBUILD_examples=ON \
            -DBUILD_tools=ON \
            -DBUILD_apps=ON \
            -DBUILD_apps_3d_rec_framework=ON \
            -DBUILD_apps_cloud_composer=ON \
            -DBUILD_apps_in_hand_scanner=ON \
            -DBUILD_apps_modeler=ON \
            -DBUILD_apps_point_cloud_editor=ON
        displayName: 'CMake Configuration'
      - script: |
          cd $BUILD_DIR
          cmake --build . -- -j2
        displayName: 'Build Library'
      - script: |
          cd $BUILD_DIR && cmake --build . -- tests
        displayName: 'Run Unit Tests'
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'CTest'
          testResultsFiles: '**/Test*.xml'
          searchFolder: '$(Agent.BuildDirectory)/build'
        condition: succeededOrFailed()
